webtalk_init -webtalk_dir C:/Users/USER/Documents/vivado/Improved Nanoprocessor/ProgramCounter/ProgramCounter.sim/sim_1/behav/xsim/xsim.dir/TB_ProgramCounter_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May  5 22:11:55 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2288692" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5cd6a477ffe35716aee35c8432ed48f9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f28e915180cc4d49abfca8c800f36228" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6852_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3591809487 -regid "" -xml C:/Users/USER/Documents/vivado/Improved Nanoprocessor/ProgramCounter/ProgramCounter.sim/sim_1/behav/xsim/xsim.dir/TB_ProgramCounter_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/USER/Documents/vivado/Improved Nanoprocessor/ProgramCounter/ProgramCounter.sim/sim_1/behav/xsim/xsim.dir/TB_ProgramCounter_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/USER/Documents/vivado/Improved Nanoprocessor/ProgramCounter/ProgramCounter.sim/sim_1/behav/xsim/xsim.dir/TB_ProgramCounter_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
