# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/.Xil/Vivado-39148-L0rd/incrSyn}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/Nanoprocessor1.cache/wt} [current_project]
set_property parent.project_path {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/Nanoprocessor1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo {l:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/Nanoprocessor1.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/Add_Sub_4.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/CLOCK.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/D_FF.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/Decoder_2_to_4.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/Decoder_3_to_8.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/FA.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/HA.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/LUT_16_7.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/MUX_2_way_3_bit.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/MUX_2_way_4_bit.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/MUX_8_to_1.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/MUX_8_way_4_bit.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/PROM.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/ProgramCounter.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/RCA_3.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/RegisterBank.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/Register_4_bit.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/needed components/ins_decoder.vhd}
  {L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Nanoprocessor/Nanoprocessor1.srcs/sources_1/new/Nanoprocessor1.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Basys3Labs.xdc}}
set_property used_in_implementation false [get_files {{L:/Documents/Xilinx/to submit/Basic Nanoprocessor/Basys3Labs.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Nanoprocessor1 -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Nanoprocessor1.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Nanoprocessor1_utilization_synth.rpt -pb Nanoprocessor1_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
